In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt

In [2]:
import os

In [3]:
from google.colab import drive, files
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [4]:

%cd '/content/drive/MyDrive/2022-2024/NEU/IE 7300/Project/EMG_data_for_gestures-master'
!ls -lrt

/content/drive/MyDrive/2022-2024/NEU/IE 7300/Project/EMG_data_for_gestures-master
total 144
drwx------ 2 root root 4096 Dec  7  2018 36
drwx------ 2 root root 4096 Dec  7  2018 35
drwx------ 2 root root 4096 Dec  7  2018 34
drwx------ 2 root root 4096 Dec  7  2018 33
drwx------ 2 root root 4096 Dec  7  2018 32
drwx------ 2 root root 4096 Dec  7  2018 31
drwx------ 2 root root 4096 Dec  7  2018 30
drwx------ 2 root root 4096 Dec  7  2018 29
drwx------ 2 root root 4096 Dec  7  2018 28
drwx------ 2 root root 4096 Dec  7  2018 27
drwx------ 2 root root 4096 Dec  7  2018 26
drwx------ 2 root root 4096 Dec  7  2018 25
drwx------ 2 root root 4096 Dec  7  2018 24
drwx------ 2 root root 4096 Dec  7  2018 23
drwx------ 2 root root 4096 Dec  7  2018 22
drwx------ 2 root root 4096 Dec  7  2018 21
drwx------ 2 root root 4096 Dec  7  2018 20
drwx------ 2 root root 4096 Dec  7  2018 19
drwx------ 2 root root 4096 Dec  7  2018 18
drwx------ 2 root root 4096 Dec  7  2018 17
drwx------ 2 root root 4096 Dec  7  2018 16
drwx------ 2 root root 4096 Dec  7  2018 15
drwx------ 2 root root 4096 Dec  7  2018 14
drwx------ 2 root root 4096 Dec  7  2018 13
drwx------ 2 root root 4096 Dec  7  2018 12
drwx------ 2 root root 4096 Dec  7  2018 11
drwx------ 2 root root 4096 Dec  7  2018 10
drwx------ 2 root root 4096 Dec  7  2018 09
drwx------ 2 root root 4096 Dec  7  2018 08
drwx------ 2 root root 4096 Dec  7  2018 07
drwx------ 2 root root 4096 Dec  7  2018 06
drwx------ 2 root root 4096 Dec  7  2018 05
drwx------ 2 root root 4096 Dec  7  2018 04
drwx------ 2 root root 4096 Dec  7  2018 03
drwx------ 2 root root 4096 Dec  7  2018 02
drwx------ 2 root root 4096 Dec  7  2018 01

In [5]:
# List out all the available files in the project's environment
files_path = set()
for dirname, _, filenames in os.walk('/content/drive/MyDrive/2022-2024/NEU/IE 7300/Project/EMG_data_for_gestures-master/'):
    for filename in filenames:
        f_path = os.path.join(dirname, filename)
        files_path.add(f_path)

In [ ]:
files_path.discard('/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/README.txt')
files_path.discard('/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/all_ext_features_data.csv')
files_path.discard('/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/Segmented_Catch22_Subject1.csv')
files_path

{'/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/01/1_raw_data_13-12_22.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/01/2_raw_data_13-13_22.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/02/1_raw_data_14-19_22.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/02/2_raw_data_14-21_22.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/03/1_raw_data_09-32_11.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/03/2_raw_data_09-34_11.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/04/1_raw_data_18-02_24.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/04/2_raw_data_18-03_24.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/05/1_raw_data_10-28_30.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/05/2_raw_data_10-29_30.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/06/1_raw_data_10-38_11.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/06/2_raw_data_10-40_11.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/07/1_raw_data_18-48_22.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/07/2_raw_data_18-50_22.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/08/1_raw_data_12-14_23.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/08/2_raw_data_12-16_23.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/09/1_raw_data_12-41_23.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/09/2_raw_data_12-43_23.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/10/1_raw_data_11-08_21.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/10/2_raw_data_11-10_21.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/11/1_raw_data_13-11_18.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/11/2_raw_data_13-13_18.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/12/1_raw_data_11-35_28.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/12/2_raw_data_11-36_28.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/13/1_raw_data_13-26_21.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/13/2_raw_data_13-29_21.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/14/1_raw_data_09-50_15.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/14/2_raw_data_09-51_15.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/15/1_raw_data_08-49_13.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/15/2_raw_data_08-51_13.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/16/1_raw_data_12-12_25.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/16/2_raw_data_12-14_25.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/17/1_raw_data_11-19_23.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/17/2_raw_data_11-20_23.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/18/1_raw_data_12-35_21.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/18/2_raw_data_12-37_21.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/19/1_raw_data_12-10_26.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/19/2_raw_data_12-11_26.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/20/1_raw_data_11-41_22.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/20/2_raw_data_11-43_22.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/21/1_raw_data_20-28_24.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/21/2_raw_data_20-30_24.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/22/1_raw_data_12-37_28.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/22/2_raw_data_12-39_28.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/23/1_raw_data_13-18_05.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/23/2_raw_data_13-19_05.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/24/1_raw_data_10-16_12.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/24/2_raw_data_10-17_12.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/25/1_raw_data_14-51_24.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/25/2_raw_data_14-53_24.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/26/1_raw_data_10-22_29.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/26/2_raw_data_10-23_29.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/27/1_raw_data_12-19_06.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/27/2_raw_data_12-20_06.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/28/1_raw_data_12-10_15.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/28/2_raw_data_12-11_15.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/29/1_raw_data_10-17_15.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/29/2_raw_data_10-18_15.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/30/1_raw_data_09-49_21.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/30/2_raw_data_09-50_21.03.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/31/1_raw_data_11-15_11.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/31/2_raw_data_11-16_11.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/32/1_raw_data_12-04_27.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/32/2_raw_data_12-06_27.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/33/1_raw_data_09-49_12.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/33/2_raw_data_09-50_12.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/34/1_raw_data_10-51_07.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/34/2_raw_data_10-53_07.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/35/1_raw_data_10-03_13.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/35/2_raw_data_10-05_13.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/36/1_raw_data_13-03_15.04.16.txt',
 '/content/drive/MyDrive/Northeastern/Projects/IE7300 Project/EMG_data_for_gestures-master/36/2_raw_data_13-04_15.04.16.txt'}

In [48]:
df_time_series = pd.DataFrame()
for id, file in enumerate(tqdm(sorted(files_path))):
    # print(file.split('/')[-2])
    sub = int(file.split('/')[-2])
    data = pd.read_csv(file, sep='\t')
    subject_id = np.ones([len(data),1], dtype=np.int16)*sub
    print('\tSubject Id: ', sub, ' Num Records: ', subject_id.shape[0])
    # Add the subject into the data
    data['subject_id'] = subject_id
    df_time_series = pd.concat([df_time_series, data], axis=0, ignore_index=True, copy=True)
    # if id%2 == 1: 
    #     all_train = pd.concat([all_train, data], axis=0, ignore_index=True, copy=True)
    # else:
    #     all_test = pd.concat([all_test, data], axis=0, ignore_index=True, copy=True)

print('Total Records: ', df_time_series.shape)

  3%|▎         | 2/72 [00:00<00:08,  8.01it/s]

	Subject Id:  1  Num Records:  63196
	Subject Id:  1  Num Records:  57974

  6%|▌         | 4/72 [00:00<00:10,  6.49it/s]

	Subject Id:  2  Num Records:  72322
	Subject Id:  2  Num Records:  64104

  8%|▊         | 6/72 [00:00<00:09,  7.01it/s]

	Subject Id:  3  Num Records:  56568
	Subject Id:  3  Num Records:  49217

 11%|█         | 8/72 [00:01<00:09,  6.84it/s]

	Subject Id:  4  Num Records:  59107
	Subject Id:  4  Num Records:  55091

 14%|█▍        | 10/72 [00:01<00:09,  6.53it/s]

	Subject Id:  5  Num Records:  57118
	Subject Id:  5  Num Records:  50130

 17%|█▋        | 12/72 [00:01<00:08,  7.07it/s]

	Subject Id:  6  Num Records:  51078
	Subject Id:  6  Num Records:  48541

 19%|█▉        | 14/72 [00:02<00:09,  6.43it/s]

	Subject Id:  7  Num Records:  68697
	Subject Id:  7  Num Records:  63943

 22%|██▏       | 16/72 [00:02<00:08,  6.51it/s]

	Subject Id:  8  Num Records:  60280
	Subject Id:  8  Num Records:  57668

 25%|██▌       | 18/72 [00:02<00:07,  7.46it/s]

	Subject Id:  9  Num Records:  62770
	Subject Id:  9  Num Records:  64877

 28%|██▊       | 20/72 [00:02<00:06,  7.65it/s]

	Subject Id:  10  Num Records:  61641
	Subject Id:  10  Num Records:  61448

 31%|███       | 22/72 [00:03<00:06,  7.54it/s]

	Subject Id:  11  Num Records:  74681
	Subject Id:  11  Num Records:  72645

 33%|███▎      | 24/72 [00:03<00:06,  7.93it/s]

	Subject Id:  12  Num Records:  65920
	Subject Id:  12  Num Records:  62631

 36%|███▌      | 26/72 [00:03<00:06,  7.13it/s]

	Subject Id:  13  Num Records:  75676
	Subject Id:  13  Num Records:  77564

 39%|███▉      | 28/72 [00:03<00:05,  7.83it/s]

	Subject Id:  14  Num Records:  52821
	Subject Id:  14  Num Records:  48182

 42%|████▏     | 30/72 [00:04<00:05,  8.27it/s]

	Subject Id:  15  Num Records:  53553
	Subject Id:  15  Num Records:  51843

 44%|████▍     | 32/72 [00:04<00:04,  8.23it/s]

	Subject Id:  16  Num Records:  55489
	Subject Id:  16  Num Records:  50012

 46%|████▌     | 33/72 [00:04<00:05,  7.61it/s]

	Subject Id:  17  Num Records:  65227
	Subject Id:  17  Num Records:  66858

 49%|████▊     | 35/72 [00:04<00:05,  7.27it/s]

	Subject Id:  18  Num Records:  62354
	Subject Id:  18  Num Records:  66958

 53%|█████▎    | 38/72 [00:05<00:04,  7.12it/s]

	Subject Id:  19  Num Records:  58818
	Subject Id:  19  Num Records:  51088

 54%|█████▍    | 39/72 [00:05<00:04,  7.11it/s]

	Subject Id:  20  Num Records:  65349
	Subject Id:  20  Num Records:  62504

 57%|█████▋    | 41/72 [00:05<00:04,  6.66it/s]

	Subject Id:  21  Num Records:  62365
	Subject Id:  21  Num Records:  56882

 61%|██████    | 44/72 [00:06<00:03,  7.02it/s]

	Subject Id:  22  Num Records:  61788
	Subject Id:  22  Num Records:  57841

 62%|██████▎   | 45/72 [00:06<00:03,  6.94it/s]

	Subject Id:  23  Num Records:  60135
	Subject Id:  23  Num Records:  55484

 65%|██████▌   | 47/72 [00:06<00:03,  6.45it/s]

	Subject Id:  24  Num Records:  61968
	Subject Id:  24  Num Records:  54972

 68%|██████▊   | 49/72 [00:06<00:03,  6.28it/s]

	Subject Id:  25  Num Records:  62681
	Subject Id:  25  Num Records:  54066

 71%|███████   | 51/72 [00:07<00:03,  6.05it/s]

	Subject Id:  26  Num Records:  56151
	Subject Id:  26  Num Records:  50003

 74%|███████▎  | 53/72 [00:07<00:03,  6.06it/s]

	Subject Id:  27  Num Records:  56688
	Subject Id:  27  Num Records:  50111

 76%|███████▋  | 55/72 [00:07<00:02,  6.04it/s]

	Subject Id:  28  Num Records:  50513
	Subject Id:  28  Num Records:  47253

 79%|███████▉  | 57/72 [00:08<00:02,  5.89it/s]

	Subject Id:  29  Num Records:  53904
	Subject Id:  29  Num Records:  52083

 82%|████████▏ | 59/72 [00:08<00:02,  5.46it/s]

	Subject Id:  30  Num Records:  77878

 83%|████████▎ | 60/72 [00:08<00:02,  5.31it/s]

	Subject Id:  30  Num Records:  70683
	Subject Id:  31  Num Records:  44927

 86%|████████▌ | 62/72 [00:09<00:01,  5.38it/s]

	Subject Id:  31  Num Records:  46096

 88%|████████▊ | 63/72 [00:09<00:01,  5.18it/s]

	Subject Id:  32  Num Records:  62719
	Subject Id:  32  Num Records:  60211

 90%|█████████ | 65/72 [00:09<00:01,  5.22it/s]

	Subject Id:  33  Num Records:  59017
	Subject Id:  33  Num Records:  53088

 93%|█████████▎| 67/72 [00:10<00:00,  5.02it/s]

	Subject Id:  34  Num Records:  79765
	Subject Id:  34  Num Records:  51438

 96%|█████████▌| 69/72 [00:10<00:00,  5.18it/s]

	Subject Id:  35  Num Records:  50417
	Subject Id:  35  Num Records:  49084

 99%|█████████▊| 71/72 [00:11<00:00,  5.22it/s]

	Subject Id:  36  Num Records:  52390
	Subject Id:  36  Num Records:  49364

100%|██████████| 72/72 [00:11<00:00,  6.42it/s]

Total Records:  (4237908, 11)

In [49]:
df_time_series.shape

(4237908, 11)

In [50]:
df_time_series['class'].unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7., nan])

In [51]:
df = df_time_series.copy(deep=True)
#df = df.drop(df[(df['class']==0) | (df['class']==7)].index)

In [52]:
df = df.drop(df[(df['class']==0) | (df['class']==7) | (df['class'].isna())].index)

In [53]:
df['class'].unique()

array([1., 2., 3., 4., 5., 6.])

In [12]:
#df_time_series=df_time_series.drop(columns=["time"])
#Class = df_time_series["class"]
#print(Class.unique())
#print("Value Count :\n", df_time_series["class"].value_counts())

[ 0.  1.  2.  3.  4.  5.  6.  7. nan]
Value Count :
 0.0    2725157
6.0     253009
5.0     251733
4.0     251570
1.0     250055
3.0     249494
2.0     243193
7.0      13696
Name: class, dtype: int64

In [54]:
##drop gesture 0 and 7 
index_numbers_1=df_time_series[df_time_series["class"]==0].index 
df_time_series.drop(index_numbers_1,inplace=True)
index_numbers_2=df_time_series[df_time_series["class"]==7].index
df_time_series.drop(index_numbers_2,inplace=True)

In [55]:
df_time_series.shape

(1499055, 11)

In [56]:
!pip install nolds
!pip install pycatch22
!pip install torchsummary
# !pip install pyeeg

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nolds in /usr/local/lib/python3.9/dist-packages (0.5.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from nolds) (67.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from nolds) (1.22.4)
Requirement already satisfied: future in /usr/local/lib/python3.9/dist-packages (from nolds) (0.18.3)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pycatch22 in /usr/local/lib/python3.9/dist-packages (0.4.2)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: torchsummary in /usr/local/lib/python3.9/dist-packages (1.5.1)

In [57]:
df_time_series['class'].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6., nan])

In [17]:
import statistics
from scipy import stats
from scipy.fft import rfft, rfftfreq
from scipy.signal import butter, filtfilt, find_peaks
import scipy
import pycatch22
import tensorflow as tf
from tensorflow import keras
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from torchsummary import summary

In [18]:
import warnings
import os
import operator
from tqdm import tqdm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pywt
import librosa
import nolds
# import pyeeg
warnings.filterwarnings('ignore')
sns.set_style('darkgrid')
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_colwidth', 500)

In [ ]:
# for subject_id in df_time_series['subject_id'].unique():
#     for channel in range(1,2):
#         if subject_id == 1:
#             sub_df = df_time_series.loc[df_time_series['subject_id']==subject_id, f'channel{channel}']
#             intervals = np.array_split(sub_df, len(sub_df)//500)
# interval = intervals[0]            
# peaks = scipy.signal.find_peaks(interval)
# peaks = np.array(peaks)
# print(peaks[0][1])
# interval = interval.reset_index()
# interval.iloc[63]

92

index       63.00000
channel1    -0.00001
Name: 63, dtype: float64

In [ ]:
# for subject_id in df_time_series['subject_id'].unique():
#     for channel in range(1,2):
#         if subject_id == 1:
#             df_time_series = df_time_series.loc[df_time_series['class']==1] 
#             sub_df = df_time_series.loc[df_time_series['subject_id']==subject_id, f'channel{channel}']
# print(sub_df)

2287    -0.00001
2288    -0.00001
2289    -0.00001
2290    -0.00001
2291    -0.00001
          ...
94903   -0.00001
94904   -0.00001
94905   -0.00001
94906   -0.00001
94907    0.00001
Name: channel1, Length: 7311, dtype: float64

In [ ]:
# df_time_series['class'].nunique()

1

In [ ]:
# print(df_time_series[df_time_series['class'] == np.nan])

Empty DataFrame
Columns: [time, channel1, channel2, channel3, channel4, channel5, channel6, channel7, channel8, class, subject_id]
Index: []

In [ ]:
# df_time_series[:5,:]

In [ ]:
# for subject_id in range(1,2):
#      for channel in range(1, 2):
#         sub_df = df_time_series.loc[df_time_series['subject_id']==subject_id, f'channel{channel}']
#         intervals = np.array_split(sub_df, len(sub_df)//600)
#         peaks, properties = scipy.signal.find_peaks(intervals[0])
#         interval = intervals[0]
#         print(interval)

2287   -0.00001
2288   -0.00001
2289   -0.00001
2290   -0.00001
2291   -0.00001
         ...
2889    0.00000
2890    0.00000
2891    0.00000
2892    0.00000
2893    0.00000
Name: channel1, Length: 607, dtype: float64

In [ ]:
# print(peaks)
# interval = intervals[0]
# interval = interval.reset_index(drop=True)
# peak = [interval[ind] for ind in peaks]
# print(peak)

[ 46  63  97 132 171 238 273 308 337 366 388 424 448 472 508 575]
[0.0, -1e-05, 0.0, 1e-05, 0.0, 1e-05, 0.0, 1e-05, 1e-05, 0.0, -1e-05, 0.0, 0.0, -1e-05, -1e-05, 1e-05]

In [19]:
def generate_segments(data_length, segment_length, span):
    # Calculate the number of segments based on the desired length of each segment
    num_segments = int(data_length / segment_length)

    # Create a list of tuples representing each segment needed for processing
    segments = []
    for i in range(num_segments):
        # Calculate the center of the segment and its range start and end positions
        segment_center = i * segment_length + int(segment_length / 2)
        segment_start = max(0, int(segment_center - span / 2))
        segment_end = min(segment_center + span / 2, data_length - 1)
        segments.append((int(segment_start), int(segment_end)))

    # Return the list of segment tuples
    return segments

In [20]:
def refactor_amplitude(channel_data, segment_ranges):
    # Initialize an empty list to hold the refactored amplitude values
    refactored_data = []

    # Iterate through each segment range and calculate the average peak amplitude within that range
    for segment_range in segment_ranges:
        segment_data = channel_data[segment_range[0]:segment_range[1]]

        # Find the peak amplitudes within the segment
        peak_indices = find_peaks(segment_data)[0]
        peaks = [segment_data[ind] for ind in peak_indices]

        # Calculate the average peak amplitude within the segment
        if len(peaks) > 0:
            avg_peak_amplitude = sum(peaks) / len(peaks)
            refactored_data.append(avg_peak_amplitude)
        else:
            # If there are no peaks within the segment, calculate the average amplitude instead
            avg_amplitude = sum(segment_data) / len(segment_data)
            refactored_data.append(avg_amplitude)

    # Return the list of refactored amplitude values
    return refactored_data

In [21]:
def refactor_labels(class_data, segment_ranges):
    # Initialize an empty list to hold the refactored label values
    refactored_class = []

    # Iterate through each segment range and calculate the mode label within that range
    for segment_range in segment_ranges:
        segment_data = class_data[segment_range[0]:segment_range[1]]

        # Find the mode label within the segment
        unique_labels, label_counts = np.unique(segment_data, return_counts=True)
        mode_label = max(dict(zip(unique_labels, label_counts)).items(), key=operator.itemgetter(1))[0]

        refactored_class.append(mode_label)

    # Return the list of refactored label values
    return refactored_class

In [40]:
df['class'].unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6., nan])

In [ ]:
# signal_interval=600
# segment_num = 320
# span=1000
# catch22_list = []
# all_subject_data = []
# CHANNELS = ["channel" + str(x) for x in range(1,9)]
# # iterate over each subject in the data
# for subject_id in df['subject_id'].unique():
#     refactored_data = pd.DataFrame(index=[], columns=[])
#     # iterate over each channel in the data
#     for channel in CHANNELS:
# #         #for target in df['class'].unique():
# #             #print(target," ")       
# #             #df1 = df.loc[df['class']==target]
#         sub_df = df.loc[df['subject_id']==subject_id, channel].values
#         # print(sub_df.shape)
#         segment_len = len(sub_df) / segment_num
#         ranges = generate_segments(len(sub_df), segment_len, span)
#         refactored_channel_data = refactor_amplitude(sub_df, ranges)
#         refactored_data[channel] = refactored_channel_data
#         refactored_data['subject_id'] = subject_id
#         sub_df2 = df.loc[df['subject_id']==subject_id, ['class', 'time']].values
#         class_refactor = refactor_labels(sub_df2[:,0], ranges)
#         time_refactor = refactor_labels(sub_df2[:,1], ranges)
#         refactored_data["time"] = time_refactor
#         refactored_data["class"] = class_refactor
#     all_subject_data.append(refactored_data)

# # Concatenate all the dataframes into a single dataframe
# concatenated_data = pd.concat(all_subject_data)

# #             # split the data into intervals of length 1024
# #             intervals = np.array_split(sub_df, len(sub_df)//signal_interval)
# #             y_segments = np.array_split(df.loc[df['subject_id']==subject_id, 'class'], len(sub_df)//signal_interval)
# #             # for each signal interval
# #             for int_idx, interval in enumerate(intervals):
# #                 # apply catch22 on the interval and compute the mean of all the features
# #                 features_interval = pycatch22.catch22_all(interval)
# #                 # compute more statistical features for the data of each channel
# #                 interval_stats = {}
# #                 class_mode = statistics.mode(y_segments[int_idx])
# #                 interval_stats['class_mode'] = class_mode
# #                 interval_stats['subject_id'] = subject_id
# #                 interval_stats['channel'] = channel
# #                 interval_stats['interval'] = int_idx
# #                 #interval_stats['mean'] = np.mean(interval)
# #                 #interval_stats['std'] = np.std(interval)
# #                 #interval_stats['var'] = np.var(interval)
# #                 interval_stats['min'] = np.min(interval)
# #                 interval_stats['max'] = np.min(interval)
# #                 #interval_stats['ptp'] = np.ptp(interval)    
# #                 interval_stats['rms'] = np.sqrt(np.mean(interval**2))    
# #                 peaks = scipy.signal.find_peaks(interval)
# #                 interval_stats['freq1'] = interval.iloc[peaks[0][1]] * 1000
# #                 interval_stats['freq2'] = interval.iloc[peaks[0][2]] * 1000
# #                 interval_stats['freq3'] = interval.iloc[peaks[0][3]] * 1000
# #                 #interval_stats['skew'] = stats.skew(interval)    
# #                 #interval_stats['kurtosis'] = stats.kurtosis(interval)    
# #                 #map feature names to feature values for each signal interval
# #                 features_mean = {feature_name: feature_value for feature_name, feature_value in zip(features_interval['names'], features_interval['values'])}
# #                 interval_dict = {**interval_stats, **features_mean}
# #                 catch22_list.append(interval_stats)

# # catch22_df = pd.DataFrame(catch22_list)

In [58]:
signal_interval=600
segment_num = 320
span=1000
catch22_list = []
CHANNELS = ["channel" + str(x) for x in range(1,9)]
data_3d = []
segments_data = []
all_subject_data = []
# iterate over each subject in the data
for subject_id in df['subject_id'].unique():
    print('Processing Subject: ', subject_id)
    refactored_data = pd.DataFrame(index=[], columns=[])
    # iterate over each channel in the data
    for channel in CHANNELS:
        sub_df = df.loc[df['subject_id']==subject_id, channel].values
        if np.isnan(sub_df).any():
            print('Error 1: ', subject_id, channel)
        segment_len = len(sub_df) / segment_num
        ranges = generate_segments(len(sub_df), segment_len, span)
        if np.isnan(ranges).any():
            print('Error 5: ', subject_id, channel)
        refactored_channel_data = refactor_amplitude(sub_df, ranges)
        if np.isnan(refactored_channel_data).any():
            print('Error 2: ', subject_id, channel)
        refactored_data[channel] = refactored_channel_data
    refactored_data['subject_id'] = subject_id
    sub_df2 = df.loc[df['subject_id']==subject_id, ['class', 'time']].values
    class_refactor = refactor_labels(sub_df2[:,0], ranges)
    if np.isnan(class_refactor).any():
        print('Error 3: ', subject_id)
    time_refactor = refactor_labels(sub_df2[:,1], ranges)
    if np.isnan(time_refactor).any():
        print('Error 4: ', subject_id)
    refactored_data["time"] = time_refactor
    refactored_data["class"] = class_refactor

    seg_data = (refactored_data['time'] - 1) // 320 + 1
    print("NaN values in seg_data: ", np.isnan(seg_data).any())
    refactored_data['segment'] = seg_data.values
    print("NaN values in refactored_data['segment']: ", np.isnan(refactored_data['segment']).any())
    if np.isnan(refactored_data).any().any():
         print('Error 6: ', subject_id)
    else:
         #Add a new column to identify the segment number
         refactored_data['segment'] = (refactored_data['time'] - 1) // (320 + 1)
         all_subject_data.append(refactored_data)
# Concatenate all the dataframes into a single dataframe
concatenated_data = pd.concat(all_subject_data)

Processing Subject:  1
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  2
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  3
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  4
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  5
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  6
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  7
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  8
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  9
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  10
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  11
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  12
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  13
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  14
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  15
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  16
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  17
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  18
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  19
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  20
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  21
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  22
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  23
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  24
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  25
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  26
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  27
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  28
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  29
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  30
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  31
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  32
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  33
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  34
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  35
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False
Processing Subject:  36
NaN values in seg_data:  False
NaN values in refactored_data['segment']:  False

In [59]:
type(seg_data)

pandas.core.series.Series

In [77]:
concatenated_data.head(20)

,channel1,channel2,channel3,channel4,channel5,channel6,channel7,channel8,subject_id,time,class,segment
0,2.258755e-22,0.000008,0.000012,0.000004,3.750000e-06,1.818182e-06,6.666667e-07,0.000003,1,2400.0,1.0,7.0
1,2.000000e-06,0.000009,0.000013,0.000006,2.857143e-06,2.000000e-06,0.000000e+00,0.000004,1,2400.0,1.0,7.0
2,1.739130e-06,0.000009,0.000013,0.000007,2.400000e-06,1.666667e-06,9.090909e-07,0.000004,1,2400.0,1.0,7.0
3,2.142857e-06,0.000011,0.000012,0.000007,2.000000e-06,8.333333e-07,7.407407e-07,0.000003,1,2400.0,1.0,7.0
4,2.222222e-06,0.000013,0.000012,0.000007,1.562500e-06,4.166667e-07,7.407407e-07,0.000003,1,2499.0,1.0,7.0
5,3.103448e-06,0.000013,0.000013,0.000008,1.290323e-06,-1.153846e-06,7.142857e-07,0.000003,1,2634.0,1.0,8.0
6,2.500000e-06,0.000012,0.000009,0.000008,9.090909e-07,0.000000e+00,2.068966e-06,0.000003,1,2772.0,1.0,8.0
7,4.400000e-06,0.000011,0.000009,0.000010,1.212121e-06,-3.448276e-07,1.034483e-06,0.000003,1,2908.0,1.0,9.0
8,4.814815e-06,0.000012,0.000011,0.000010,8.823529e-07,-5.464729e-23,2.000000e-06,0.000002,1,3044.0,1.0,9.0
9,3.333333e-06,0.000012,0.000010,0.000009,1.212121e-06,3.448276e-07,2.258065e-06,0.000002,1,3178.0,1.0,9.0
10,3.703704e-06,0.000012,0.000011,0.000007,9.375000e-07,-6.274318e-23,2.413793e-06,0.000002,1,3319.0,1.0,10.0
11,4.482759e-06,0.000011,0.000012,0.000009,9.375000e-07,6.666667e-07,3.870968e-06,0.000002,1,3455.0,1.0,10.0
12,7.741935e-06,0.000011,0.000018,0.000013,5.000000e-06,1.612903e-06,-2.903226e-06,0.000007,1,3595.0,1.0,11.0
13,2.969697e-05,0.000017,0.000037,0.000031,2.218750e-05,4.774194e-05,4.781250e-05,0.000039,1,3731.0,1.0,11.0
14,4.562500e-05,0.000031,0.000061,0.000046,3.656250e-05,7.451613e-05,8.468750e-05,0.000077,1,3870.0,1.0,12.0
15,8.272727e-05,0.000043,0.000075,0.000069,5.466667e-05,8.586207e-05,1.018750e-04,0.000095,1,4009.0,1.0,12.0
16,1.285714e-04,0.000057,0.000094,0.000087,7.862069e-05,9.281250e-05,1.431250e-04,0.000132,1,4145.0,2.0,12.0
17,1.643750e-04,0.000079,0.000131,0.000111,9.592593e-05,1.093750e-04,1.712903e-04,0.000152,1,4281.0,2.0,13.0
18,1.948387e-04,0.000095,0.000174,0.000136,1.130769e-04,1.140625e-04,1.861290e-04,0.000161,1,4418.0,2.0,13.0
19,2.246667e-04,0.000108,0.000202,0.000160,1.300000e-04,1.460000e-04,2.193333e-04,0.000185,1,4554.0,2.0,14.0

In [61]:
concatenated_data.shape

(11520, 12)

In [62]:
#df_time_series=df_time_series.drop(columns=["time"])
Class = concatenated_data["class"]
print(Class.unique())
print("Value Count :\n", concatenated_data["class"].value_counts())

[1. 2. 3. 4. 5. 6.]
Value Count :
 6.0    1942
4.0    1937
5.0    1926
1.0    1925
3.0    1911
2.0    1879
Name: class, dtype: int64

In [63]:
concatenated_data[concatenated_data.segment.isna()]

Empty DataFrame
Columns: [channel1, channel2, channel3, channel4, channel5, channel6, channel7, channel8, subject_id, time, class, segment]
Index: []

In [64]:
concatenated_data.shape

(11520, 12)

In [66]:
concatenated_data.groupby('subject_id')['segment'].nunique().values[:-1]

array([133, 114, 100, 111, 100, 107, 157, 113, 115,  84,  87,  93, 189,
       101, 115, 106, 108, 142, 113, 135, 115, 111, 121, 115, 116, 115,
       104,  88, 122, 124,  85, 118, 107, 123, 115])

In [68]:
concatenated_data.groupby('subject_id')['segment'].nunique()

subject_id
1     133
2     114
3     100
4     111
5     100
6     107
7     157
8     113
9     115
10     84
11     87
12     93
13    189
14    101
15    115
16    106
17    108
18    142
19    113
20    135
21    115
22    111
23    121
24    115
25    116
26    115
27    104
28     88
29    122
30    124
31     85
32    118
33    107
34    123
35    115
36    105
Name: segment, dtype: int64

In [78]:
concatenated_data.head(10)

,channel1,channel2,channel3,channel4,channel5,channel6,channel7,channel8,subject_id,time,class,segment
0,2.258755e-22,0.000008,0.000012,0.000004,3.750000e-06,1.818182e-06,6.666667e-07,0.000003,1,2400.0,1.0,7.0
1,2.000000e-06,0.000009,0.000013,0.000006,2.857143e-06,2.000000e-06,0.000000e+00,0.000004,1,2400.0,1.0,7.0
2,1.739130e-06,0.000009,0.000013,0.000007,2.400000e-06,1.666667e-06,9.090909e-07,0.000004,1,2400.0,1.0,7.0
3,2.142857e-06,0.000011,0.000012,0.000007,2.000000e-06,8.333333e-07,7.407407e-07,0.000003,1,2400.0,1.0,7.0
4,2.222222e-06,0.000013,0.000012,0.000007,1.562500e-06,4.166667e-07,7.407407e-07,0.000003,1,2499.0,1.0,7.0
5,3.103448e-06,0.000013,0.000013,0.000008,1.290323e-06,-1.153846e-06,7.142857e-07,0.000003,1,2634.0,1.0,8.0
6,2.500000e-06,0.000012,0.000009,0.000008,9.090909e-07,0.000000e+00,2.068966e-06,0.000003,1,2772.0,1.0,8.0
7,4.400000e-06,0.000011,0.000009,0.000010,1.212121e-06,-3.448276e-07,1.034483e-06,0.000003,1,2908.0,1.0,9.0
8,4.814815e-06,0.000012,0.000011,0.000010,8.823529e-07,-5.464729e-23,2.000000e-06,0.000002,1,3044.0,1.0,9.0
9,3.333333e-06,0.000012,0.000010,0.000009,1.212121e-06,3.448276e-07,2.258065e-06,0.000002,1,3178.0,1.0,9.0

In [83]:
concatenated_data.iloc[:,0:8] = (concatenated_data.iloc[:,0:8] - np.mean(concatenated_data.iloc[:,0:8], axis=0)) / np.std(concatenated_data.iloc[:,0:8], axis=0)

In [91]:
import numpy as np

X = concatenated_data[CHANNELS].values
n_segments = concatenated_data.groupby('subject_id')['segment'].nunique().values
#X_3D = np.matrix([np.split(i, [*range(1,j+1)] * 320) for i,j in zip(np.split(X, np.cumsum(n_segments) * 320),n_segments)])
data_list = []
for i in concatenated_data['subject_id'].unique():
    subject_data = concatenated_data[(concatenated_data['subject_id'] == i)] 
    segment_data = []
    for j in subject_data['segment'].unique():
        temp = subject_data[subject_data['segment'] == j].iloc[:,0:8]
        segment_data.append(temp.values)
    data_list.append(np.array(segment_data))
data_array = np.array(data_list)

In [97]:
data_array[2].shape

(100,)

In [ ]:
X_3D = np.zeros((len(n_segments), 320, 8))

idx = 0
for i, n_seg in enumerate(n_segments):
    X_sub = X[idx:idx+n_seg,:]
    padded_X_sub = np.pad(X_sub, ((0, 320-n_seg), (0, 0)), mode='constant')
    X_3D[i,:,:] = np.reshape(padded_X_sub, (320, 8))
    idx += n_seg

print(f"X_3D shape: {X_3D.shape}")

X_3D shape: (47, 320, 8)

In [ ]:
print(ranges)

[(0, 658), (0, 975), (293, 1293), (611, 1611), (929, 1929), (1247, 2247), (1565, 2565), (1883, 2883), (2201, 3201), (2519, 3519), (2837, 3837), (3155, 4155), (3473, 4473), (3791, 4791), (4109, 5109), (4427, 5427), (4745, 5745), (5063, 6063), (5381, 6381), (5699, 6699), (6017, 7017), (6335, 7335), (6653, 7653), (6971, 7971), (7289, 8289), (7607, 8607), (7925, 8925), (8243, 9243), (8561, 9561), (8879, 9879), (9197, 10197), (9515, 10515), (9833, 10833), (10151, 11151), (10469, 11469), (10787, 11787), (11105, 12105), (11423, 12423), (11741, 12741), (12059, 13059), (12377, 13377), (12695, 13695), (13013, 14013), (13331, 14331), (13649, 14649), (13967, 14967), (14285, 15285), (14603, 15603), (14921, 15921), (15239, 16239), (15557, 16557), (15875, 16875), (16193, 17193), (16511, 17511), (16828, 17828), (17146, 18146), (17464, 18464), (17782, 18782), (18100, 19100), (18418, 19418), (18736, 19736), (19054, 20054), (19372, 20372), (19690, 20690), (20008, 21008), (20326, 21326), (20644, 21644), (20962, 21962), (21280, 22280), (21598, 22598), (21916, 22916), (22234, 23234), (22552, 23552), (22870, 23870), (23188, 24188), (23506, 24506), (23824, 24824), (24142, 25142), (24460, 25460), (24778, 25778), (25096, 26096), (25414, 26414), (25732, 26732), (26050, 27050), (26368, 27368), (26686, 27686), (27004, 28004), (27322, 28322), (27640, 28640), (27958, 28958), (28276, 29276), (28594, 29594), (28912, 29912), (29230, 30230), (29548, 30548), (29866, 30866), (30184, 31184), (30502, 31502), (30820, 31820), (31138, 32138), (31456, 32456), (31774, 32774), (32092, 33092), (32410, 33410), (32728, 33728), (33046, 34046), (33364, 34364), (33681, 34681), (33999, 34999), (34317, 35317), (34635, 35635), (34953, 35953), (35271, 36271), (35589, 36589), (35907, 36907), (36225, 37225), (36543, 37543), (36861, 37861), (37179, 38179), (37497, 38497), (37815, 38815), (38133, 39133), (38451, 39451), (38769, 39769), (39087, 40087), (39405, 40405), (39723, 40723), (40041, 41041), (40359, 41359), (40677, 41677), (40995, 41995), (41313, 42313), (41631, 42631), (41949, 42949), (42267, 43267), (42585, 43585), (42903, 43903), (43221, 44221), (43539, 44539), (43857, 44857), (44175, 45175), (44493, 45493), (44811, 45811), (45129, 46129), (45447, 46447), (45765, 46765), (46083, 47083), (46401, 47401), (46719, 47719), (47037, 48037), (47355, 48355), (47673, 48673), (47991, 48991), (48309, 49309), (48627, 49627), (48945, 49945), (49263, 50263), (49581, 50581), (49899, 50899), (50217, 51217), (50535, 51535), (50852, 51852), (51170, 52170), (51488, 52488), (51806, 52806), (52124, 53124), (52442, 53442), (52760, 53760), (53078, 54078), (53396, 54396), (53714, 54714), (54032, 55032), (54350, 55350), (54668, 55668), (54986, 55986), (55304, 56304), (55622, 56622), (55940, 56940), (56258, 57258), (56576, 57576), (56894, 57894), (57212, 58212), (57530, 58530), (57848, 58848), (58166, 59166), (58484, 59484), (58802, 59802), (59120, 60120), (59438, 60438), (59756, 60756), (60074, 61074), (60392, 61392), (60710, 61710), (61028, 62028), (61346, 62346), (61664, 62664), (61982, 62982), (62300, 63300), (62618, 63618), (62936, 63936), (63254, 64254), (63572, 64572), (63890, 64890), (64208, 65208), (64526, 65526), (64844, 65844), (65162, 66162), (65480, 66480), (65798, 66798), (66116, 67116), (66434, 67434), (66752, 67752), (67070, 68070), (67388, 68388), (67705, 68705), (68023, 69023), (68341, 69341), (68659, 69659), (68977, 69977), (69295, 70295), (69613, 70613), (69931, 70931), (70249, 71249), (70567, 71567), (70885, 71885), (71203, 72203), (71521, 72521), (71839, 72839), (72157, 73157), (72475, 73475), (72793, 73793), (73111, 74111), (73429, 74429), (73747, 74747), (74065, 75065), (74383, 75383), (74701, 75701), (75019, 76019), (75337, 76337), (75655, 76655), (75973, 76973), (76291, 77291), (76609, 77609), (76927, 77927), (77245, 78245), (77563, 78563), (77881, 78881), (78199, 79199), (78517, 79517), (78835, 79835), (79153, 80153), (79471, 80471), (79789, 80789), (80107, 81107), (80425, 81425), (80743, 81743), (81061, 82061), (81379, 82379), (81697, 82697), (82015, 83015), (82333, 83333), (82651, 83651), (82969, 83969), (83287, 84287), (83605, 84605), (83923, 84923), (84241, 85241), (84558, 85558), (84876, 85876), (85194, 86194), (85512, 86512), (85830, 86830), (86148, 87148), (86466, 87466), (86784, 87784), (87102, 88102), (87420, 88420), (87738, 88738), (88056, 89056), (88374, 89374), (88692, 89692), (89010, 90010), (89328, 90328), (89646, 90646), (89964, 90964), (90282, 91282), (90600, 91600), (90918, 91918), (91236, 92236), (91554, 92554), (91872, 92872), (92190, 93190), (92508, 93508), (92826, 93826), (93144, 94144), (93462, 94462), (93780, 94780), (94098, 95098), (94416, 95416), (94734, 95734), (95052, 96052), (95370, 96370), (95688, 96688), (96006, 97006), (96324, 97324), (96642, 97642), (96960, 97960), (97278, 98278), (97596, 98596), (97914, 98914), (98232, 99232), (98550, 99550), (98868, 99868), (99186, 100186), (99504, 100504), (99822, 100822), (100140, 101140), (100458, 101458), (100776, 101753), (101094, 101753)]

In [ ]:
sub_df2 = df.loc[df['subject_id']==36, ['class', 'time']].values
print(sub_df2.shape)

(101754, 2)

In [ ]:
refactor_labels(sub_df2[:,0], ranges)

In [ ]:
print(df.shape)
print(len(df["time"].values[:]))

(4224212, 11)
4224212

In [ ]:
len(refactor_labels(df["time"].values[:], ranges))

320

In [ ]:
(refactored_data['time'] - 1) // 320 + 1

0        1.0
1        1.0
2        2.0
3        3.0
4        4.0
       ...
315    153.0
316    155.0
317    156.0
318    157.0
319    158.0
Name: time, Length: 320, dtype: float64

In [ ]:
concatenated_data.shape

(11520, 11)

In [ ]:
print(concatenated_data.iloc[400:410,:])

    channel1  subject_id     time  class  channel2  channel3  channel4  \
80  0.000037           2  34836.0    0.0  0.000039  0.000063  0.000210
81  0.000023           2  35280.0    0.0  0.000036  0.000049  0.000198
82  0.000031           2  35722.0    0.0  0.000029  0.000047  0.000191
83  0.000035           2  36157.0    0.0  0.000027  0.000048  0.000161
84  0.000024           2  36592.0    0.0  0.000025  0.000038  0.000139
85  0.000020           2  37029.0    0.0  0.000025  0.000032  0.000176
86  0.000019           2  37464.0    0.0  0.000020  0.000029  0.000178
87  0.000022           2  37901.0    0.0  0.000021  0.000031  0.000158
88  0.000022           2  38336.0    6.0  0.000025  0.000032  0.000140
89  0.000016           2  38774.0    6.0  0.000025  0.000032  0.000145

    channel5  channel6  channel7  channel8
80  0.000266  0.000109  0.000173  0.000081
81  0.000295  0.000105  0.000168  0.000082
82  0.000227  0.000090  0.000178  0.000083
83  0.000170  0.000087  0.000159  0.000081
84  0.000147  0.000076  0.000164  0.000089
85  0.000159  0.000065  0.000178  0.000096
86  0.000152  0.000071  0.000162  0.000068
87  0.000118  0.000092  0.000180  0.000060
88  0.000113  0.000080  0.000137  0.000057
89  0.000131  0.000074  0.000134  0.000058

In [ ]:
data_array = concatenated_data.to_numpy()

samples = data_array.shape[0]
timesteps = int(segment_num)
features = len(CHANNELS)
print(type(samples), type(timesteps))
data_3d = data_array.reshape(samples, timesteps, 11)
print(data_3d.shape)

<class 'int'> <class 'int'>

ValueError: ignored

In [ ]:
print(refactored_data['class'].value_counts())

0.0    206
1.0     23
2.0     22
3.0     19
5.0     17
6.0     17
4.0     16
Name: class, dtype: int64

In [ ]:
ranges

[(0, 658),
 (0, 975),
 (293, 1293),
 (611, 1611),
 (929, 1929),
 (1247, 2247),
 (1565, 2565),
 (1883, 2883),
 (2201, 3201),
 (2519, 3519),
 (2837, 3837),
 (3155, 4155),
 (3473, 4473),
 (3791, 4791),
 (4109, 5109),
 (4427, 5427),
 (4745, 5745),
 (5063, 6063),
 (5381, 6381),
 (5699, 6699),
 (6017, 7017),
 (6335, 7335),
 (6653, 7653),
 (6971, 7971),
 (7289, 8289),
 (7607, 8607),
 (7925, 8925),
 (8243, 9243),
 (8561, 9561),
 (8879, 9879),
 (9197, 10197),
 (9515, 10515),
 (9833, 10833),
 (10151, 11151),
 (10469, 11469),
 (10787, 11787),
 (11105, 12105),
 (11423, 12423),
 (11741, 12741),
 (12059, 13059),
 (12377, 13377),
 (12695, 13695),
 (13013, 14013),
 (13331, 14331),
 (13649, 14649),
 (13967, 14967),
 (14285, 15285),
 (14603, 15603),
 (14921, 15921),
 (15239, 16239),
 (15557, 16557),
 (15875, 16875),
 (16193, 17193),
 (16511, 17511),
 (16828, 17828),
 (17146, 18146),
 (17464, 18464),
 (17782, 18782),
 (18100, 19100),
 (18418, 19418),
 (18736, 19736),
 (19054, 20054),
 (19372, 20372),
 (19690, 20690),
 (20008, 21008),
 (20326, 21326),
 (20644, 21644),
 (20962, 21962),
 (21280, 22280),
 (21598, 22598),
 (21916, 22916),
 (22234, 23234),
 (22552, 23552),
 (22870, 23870),
 (23188, 24188),
 (23506, 24506),
 (23824, 24824),
 (24142, 25142),
 (24460, 25460),
 (24778, 25778),
 (25096, 26096),
 (25414, 26414),
 (25732, 26732),
 (26050, 27050),
 (26368, 27368),
 (26686, 27686),
 (27004, 28004),
 (27322, 28322),
 (27640, 28640),
 (27958, 28958),
 (28276, 29276),
 (28594, 29594),
 (28912, 29912),
 (29230, 30230),
 (29548, 30548),
 (29866, 30866),
 (30184, 31184),
 (30502, 31502),
 (30820, 31820),
 (31138, 32138),
 (31456, 32456),
 (31774, 32774),
 (32092, 33092),
 (32410, 33410),
 (32728, 33728),
 (33046, 34046),
 (33364, 34364),
 (33681, 34681),
 (33999, 34999),
 (34317, 35317),
 (34635, 35635),
 (34953, 35953),
 (35271, 36271),
 (35589, 36589),
 (35907, 36907),
 (36225, 37225),
 (36543, 37543),
 (36861, 37861),
 (37179, 38179),
 (37497, 38497),
 (37815, 38815),
 (38133, 39133),
 (38451, 39451),
 (38769, 39769),
 (39087, 40087),
 (39405, 40405),
 (39723, 40723),
 (40041, 41041),
 (40359, 41359),
 (40677, 41677),
 (40995, 41995),
 (41313, 42313),
 (41631, 42631),
 (41949, 42949),
 (42267, 43267),
 (42585, 43585),
 (42903, 43903),
 (43221, 44221),
 (43539, 44539),
 (43857, 44857),
 (44175, 45175),
 (44493, 45493),
 (44811, 45811),
 (45129, 46129),
 (45447, 46447),
 (45765, 46765),
 (46083, 47083),
 (46401, 47401),
 (46719, 47719),
 (47037, 48037),
 (47355, 48355),
 (47673, 48673),
 (47991, 48991),
 (48309, 49309),
 (48627, 49627),
 (48945, 49945),
 (49263, 50263),
 (49581, 50581),
 (49899, 50899),
 (50217, 51217),
 (50535, 51535),
 (50852, 51852),
 (51170, 52170),
 (51488, 52488),
 (51806, 52806),
 (52124, 53124),
 (52442, 53442),
 (52760, 53760),
 (53078, 54078),
 (53396, 54396),
 (53714, 54714),
 (54032, 55032),
 (54350, 55350),
 (54668, 55668),
 (54986, 55986),
 (55304, 56304),
 (55622, 56622),
 (55940, 56940),
 (56258, 57258),
 (56576, 57576),
 (56894, 57894),
 (57212, 58212),
 (57530, 58530),
 (57848, 58848),
 (58166, 59166),
 (58484, 59484),
 (58802, 59802),
 (59120, 60120),
 (59438, 60438),
 (59756, 60756),
 (60074, 61074),
 (60392, 61392),
 (60710, 61710),
 (61028, 62028),
 (61346, 62346),
 (61664, 62664),
 (61982, 62982),
 (62300, 63300),
 (62618, 63618),
 (62936, 63936),
 (63254, 64254),
 (63572, 64572),
 (63890, 64890),
 (64208, 65208),
 (64526, 65526),
 (64844, 65844),
 (65162, 66162),
 (65480, 66480),
 (65798, 66798),
 (66116, 67116),
 (66434, 67434),
 (66752, 67752),
 (67070, 68070),
 (67388, 68388),
 (67705, 68705),
 (68023, 69023),
 (68341, 69341),
 (68659, 69659),
 (68977, 69977),
 (69295, 70295),
 (69613, 70613),
 (69931, 70931),
 (70249, 71249),
 (70567, 71567),
 (70885, 71885),
 (71203, 72203),
 (71521, 72521),
 (71839, 72839),
 (72157, 73157),
 (72475, 73475),
 (72793, 73793),
 (73111, 74111),
 (73429, 74429),
 (73747, 74747),
 (74065, 75065),
 (74383, 75383),
 (74701, 75701),
 (75019, 76019),
 (75337, 76337),
 (75655, 76655),
 (75973, 76973),
 (76291, 77291),
 (76609, 77609),
 (76927, 77927),
 (77245, 78245),
 (77563, 78563),
 (77881, 78881),
 (78199, 79199),
 (78517, 79517),
 (78835, 79835),
 (79153, 80153),
 (79471, 80471),
 (79789, 80789),
 (80107, 81107),
 (80425, 81425),
 (80743, 81743),
 (81061, 82061),
 (81379, 82379),
 (81697, 82697),
 (82015, 83015),
 (82333, 83333),
 (82651, 83651),
 (82969, 83969),
 (83287, 84287),
 (83605, 84605),
 (83923, 84923),
 (84241, 85241),
 (84558, 85558),
 (84876, 85876),
 (85194, 86194),
 (85512, 86512),
 (85830, 86830),
 (86148, 87148),
 (86466, 87466),
 (86784, 87784),
 (87102, 88102),
 (87420, 88420),
 (87738, 88738),
 (88056, 89056),
 (88374, 89374),
 (88692, 89692),
 (89010, 90010),
 (89328, 90328),
 (89646, 90646),
 (89964, 90964),
 (90282, 91282),
 (90600, 91600),
 (90918, 91918),
 (91236, 92236),
 (91554, 92554),
 (91872, 92872),
 (92190, 93190),
 (92508, 93508),
 (92826, 93826),
 (93144, 94144),
 (93462, 94462),
 (93780, 94780),
 (94098, 95098),
 (94416, 95416),
 (94734, 95734),
 (95052, 96052),
 (95370, 96370),
 (95688, 96688),
 (96006, 97006),
 (96324, 97324),
 (96642, 97642),
 (96960, 97960),
 (97278, 98278),
 (97596, 98596),
 (97914, 98914),
 (98232, 99232),
 (98550, 99550),
 (98868, 99868),
 (99186, 100186),
 (99504, 100504),
 (99822, 100822),
 (100140, 101140),
 (100458, 101458),
 (100776, 101753),
 (101094, 101753)]

In [ ]:
def catch22_features(df, signal_interval=600):
    catch22_list = []
    # iterate over each subject in the data
    for subject_id in df['subject_id'].unique():
        # iterate over each channel in the data
        for channel in range(1, 9):
            #for target in df['class'].unique():
                #print(target," ")       
                #df1 = df.loc[df['class']==target]
                sub_df = df.loc[df['subject_id']==subject_id, f'channel{channel}']
                # split the data into intervals of length 1024
                intervals = np.array_split(sub_df, len(sub_df)//signal_interval)
                y_segments = np.array_split(df.loc[df['subject_id']==subject_id, 'class'], len(sub_df)//signal_interval)
                # for each signal interval
                for int_idx, interval in enumerate(intervals):
                    # apply catch22 on the interval and compute the mean of all the features
                    features_interval = pycatch22.catch22_all(interval)
                    # compute more statistical features for the data of each channel
                    interval_stats = {}
                    class_mode = statistics.mode(y_segments[int_idx])
                    interval_stats['class_mode'] = class_mode
                    interval_stats['subject_id'] = subject_id
                    interval_stats['channel'] = channel
                    interval_stats['interval'] = int_idx
                    #interval_stats['mean'] = np.mean(interval)
                    #interval_stats['std'] = np.std(interval)
                    #interval_stats['var'] = np.var(interval)
                    interval_stats['min'] = np.min(interval)
                    interval_stats['max'] = np.min(interval)
                    #interval_stats['ptp'] = np.ptp(interval)    
                    interval_stats['rms'] = np.sqrt(np.mean(interval**2))    
                    peaks = scipy.signal.find_peaks(interval)
                    interval_stats['freq1'] = interval.iloc[peaks[0][1]] * 1000
                    interval_stats['freq2'] = interval.iloc[peaks[0][2]] * 1000
                    interval_stats['freq3'] = interval.iloc[peaks[0][3]] * 1000
                    #interval_stats['skew'] = stats.skew(interval)    
                    #interval_stats['kurtosis'] = stats.kurtosis(interval)    
                    #map feature names to feature values for each signal interval
                    features_mean = {feature_name: feature_value for feature_name, feature_value in zip(features_interval['names'], features_interval['values'])}
                    interval_dict = {**interval_stats, **features_mean}
                    catch22_list.append(interval_stats)

    catch22_df = pd.DataFrame(catch22_list)
    return catch22_df

In [ ]:
catch22_data = catch22_features(df_time_series)

In [ ]:
catch22_data

,class_mode,subject_id,channel,interval,min,max,rms,freq1,freq2,freq3
0,1.0,1,1,0,-0.00003,-0.00003,0.000015,-0.01,0.00,0.01
1,1.0,1,1,1,-0.00004,-0.00004,0.000016,0.00,0.02,0.01
2,1.0,1,1,2,-0.00004,-0.00004,0.000014,0.00,0.00,0.02
3,2.0,1,1,3,-0.00111,-0.00111,0.000228,0.02,0.00,0.00
4,2.0,1,1,4,-0.00063,-0.00063,0.000225,0.18,0.24,0.01
...,...,...,...,...,...,...,...,...,...,...
19827,5.0,36,8,55,-0.00009,-0.00009,0.000034,0.02,0.01,0.02
19828,5.0,36,8,56,-0.00008,-0.00008,0.000029,0.02,0.03,0.01
19829,6.0,36,8,57,-0.00019,-0.00019,0.000059,0.01,0.03,0.02
19830,6.0,36,8,58,-0.00030,-0.00030,0.000093,0.07,0.14,0.02
19831,6.0,36,8,59,-0.00031,-0.00031,0.000086,0.07,0.10,0.05

In [ ]:
##pivoting channle to columns
pivoted_catch22 = catch22_data.pivot(index = ['class_mode','subject_id','interval'],columns='channel')

In [ ]:
pivoted_catch22 = pivoted_catch22.reset_index()

In [ ]:
pivoted_catch22

        class_mode subject_id interval      min                             \
channel                                       1        2        3        4
0              1.0          1        0 -0.00003 -0.00007 -0.00007 -0.00005
1              1.0          1        1 -0.00004 -0.00006 -0.00008 -0.00007
2              1.0          1        2 -0.00004 -0.00007 -0.00008 -0.00005
3              1.0          1       19 -0.00004 -0.00008 -0.00009 -0.00006
4              1.0          1       20 -0.00003 -0.00010 -0.00009 -0.00007
...            ...        ...      ...      ...      ...      ...      ...
2474           6.0         36       44 -0.00032 -0.00017 -0.00009 -0.00009
2475           6.0         36       45 -0.00035 -0.00014 -0.00006 -0.00008
2476           6.0         36       57 -0.00024 -0.00021 -0.00012 -0.00020
2477           6.0         36       58 -0.00016 -0.00007 -0.00006 -0.00011
2478           6.0         36       59 -0.00042 -0.00008 -0.00006 -0.00014

                                                 max                    \
channel        5        6        7        8        1        2        3
0       -0.00004 -0.00003 -0.00003 -0.00003 -0.00003 -0.00007 -0.00007
1       -0.00004 -0.00004 -0.00003 -0.00004 -0.00004 -0.00006 -0.00008
2       -0.00003 -0.00004 -0.00003 -0.00004 -0.00004 -0.00007 -0.00008
3       -0.00004 -0.00006 -0.00003 -0.00003 -0.00004 -0.00008 -0.00009
4       -0.00004 -0.00004 -0.00004 -0.00005 -0.00003 -0.00010 -0.00009
...          ...      ...      ...      ...      ...      ...      ...
2474    -0.00030 -0.00022 -0.00032 -0.00032 -0.00032 -0.00017 -0.00009
2475    -0.00018 -0.00015 -0.00018 -0.00033 -0.00035 -0.00014 -0.00006
2476    -0.00035 -0.00054 -0.00014 -0.00019 -0.00024 -0.00021 -0.00012
2477    -0.00027 -0.00027 -0.00021 -0.00030 -0.00016 -0.00007 -0.00006
2478    -0.00028 -0.00055 -0.00023 -0.00031 -0.00042 -0.00008 -0.00006

                                                           rms            \
channel        4        5        6        7        8         1         2
0       -0.00005 -0.00004 -0.00003 -0.00003 -0.00003  0.000015  0.000025
1       -0.00007 -0.00004 -0.00004 -0.00003 -0.00004  0.000016  0.000023
2       -0.00005 -0.00003 -0.00004 -0.00003 -0.00004  0.000014  0.000024
3       -0.00006 -0.00004 -0.00006 -0.00003 -0.00003  0.000017  0.000031
4       -0.00007 -0.00004 -0.00004 -0.00004 -0.00005  0.000015  0.000032
...          ...      ...      ...      ...      ...       ...       ...
2474    -0.00009 -0.00030 -0.00022 -0.00032 -0.00032  0.000116  0.000071
2475    -0.00008 -0.00018 -0.00015 -0.00018 -0.00033  0.000068  0.000038
2476    -0.00020 -0.00035 -0.00054 -0.00014 -0.00019  0.000066  0.000074
2477    -0.00011 -0.00027 -0.00027 -0.00021 -0.00030  0.000047  0.000029
2478    -0.00014 -0.00028 -0.00055 -0.00023 -0.00031  0.000116  0.000027

                                                                    freq1  \
channel         3         4         5         6         7         8     1
0        0.000031  0.000019  0.000015  0.000013  0.000014  0.000014 -0.01
1        0.000024  0.000023  0.000017  0.000014  0.000013  0.000015  0.00
2        0.000029  0.000019  0.000015  0.000015  0.000014  0.000014  0.00
3        0.000042  0.000022  0.000015  0.000020  0.000015  0.000014 -0.01
4        0.000052  0.000023  0.000014  0.000015  0.000016  0.000017 -0.01
...           ...       ...       ...       ...       ...       ...   ...
2474     0.000037  0.000041  0.000129  0.000096  0.000118  0.000117 -0.05
2475     0.000027  0.000033  0.000101  0.000074  0.000066  0.000070  0.03
2476     0.000037  0.000081  0.000169  0.000141  0.000054  0.000059 -0.01
2477     0.000026  0.000050  0.000116  0.000161  0.000082  0.000093  0.01
2478     0.000028  0.000042  0.000161  0.000161  0.000085  0.000086  0.02

                                                  freq2                    \
channel     2     3     4     5     6     7     8     1     2     3     4
0       -0.01  0.04  0.00  0.01  0.00 -0.01  0.00  0.00 -0.01 -0.03  0.00
1        0.01  0.00  0.02  0.00  0.00  0.00  0.00  0.02  0.00  0.03  0.02
2       -0.01  0.00  0.01  0.00  0.01  0.00  0.00  0.00  0.01 -0.02  0.02
3       -0.02  0.01 -0.01  0.00  0.00  0.00  0.00  0.00  0.02  0.02  0.02
4        0.02  0.03  0.01  0.00 -0.01  0.01 -0.01  0.01  0.00  0.03  0.02
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
2474     0.04  0.01  0.04  0.02  0.09  0.10  0.33  0.27  0.04  0.03  0.01
2475     0.02  0.03  0.02  0.01  0.08  0.14 -0.05  0.04  0.03  0.06  0.00
2476     0.19  0.04  0.02  0.23  0.04 -0.02  0.01  0.21  0.10  0.10  0.00
2477     0.01  0.01  0.03  0.09  0.01  0.03  0.07 -0.01  0.01  0.03  0.04
2478     0.01 -0.01 -0.01  0.25  0.17  0.02  0.07 -0.01  0.00  0.00  0.04

                                freq3                                      \
channel     5     6     7     8     1     2     3     4     5     6     7
0        0.01  0.02  0.00  0.01  0.01  0.00  0.04 -0.01 -0.01  0.01  0.01
1        0.00  0.00  0.00  0.00  0.01  0.03  0.02  0.01 -0.01  0.00  0.00
2        0.00 -0.01  0.00  0.00  0.02 -0.01 -0.01  0.00  0.00  0.00  0.00
3       -0.01  0.00  0.01  0.00  0.00  0.01  0.02  0.01  0.01  0.00  0.01
4        0.01  0.00  0.01  0.01  0.00  0.03 -0.01  0.01  0.02  0.01  0.01
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
2474     0.31  0.15  0.16  0.10  0.10  0.02  0.01  0.00  0.08  0.00 -0.07
2475    -0.02  0.11  0.15  0.03  0.05  0.29  0.04  0.05  0.02  0.05  0.05
2476     0.19  0.01 -0.01  0.03  0.10  0.01  0.09  0.11  0.00  0.03  0.00
2477     0.07  0.12  0.08  0.14  0.01 -0.01 -0.01  0.01  0.13  0.09  0.06
2478     0.09 -0.05  0.00  0.10  0.03  0.03  0.01  0.04  0.09 -0.01  0.07


channel     8
0        0.01
1        0.00
2        0.01
3        0.01
4        0.00
...       ...
2474     0.13
2475     0.04
2476     0.02
2477     0.02
2478     0.05

[2479 rows x 51 columns]

In [ ]:
m = {t: '_'.join(str(t)) for t in pivoted_catch22.columns}
final_catch22 = pivoted_catch22.groupby(m, axis=1).mean()

In [ ]:
final_catch22

,"(_'_c_l_a_s_s___m_o_d_e_'_,_ _'_'_)","(_'_f_r_e_q_1_'_,_ _1_)","(_'_f_r_e_q_1_'_,_ _2_)","(_'_f_r_e_q_1_'_,_ _3_)","(_'_f_r_e_q_1_'_,_ _4_)","(_'_f_r_e_q_1_'_,_ _5_)","(_'_f_r_e_q_1_'_,_ _6_)","(_'_f_r_e_q_1_'_,_ _7_)","(_'_f_r_e_q_1_'_,_ _8_)","(_'_f_r_e_q_2_'_,_ _1_)","(_'_f_r_e_q_2_'_,_ _2_)","(_'_f_r_e_q_2_'_,_ _3_)","(_'_f_r_e_q_2_'_,_ _4_)","(_'_f_r_e_q_2_'_,_ _5_)","(_'_f_r_e_q_2_'_,_ _6_)","(_'_f_r_e_q_2_'_,_ _7_)","(_'_f_r_e_q_2_'_,_ _8_)","(_'_f_r_e_q_3_'_,_ _1_)","(_'_f_r_e_q_3_'_,_ _2_)","(_'_f_r_e_q_3_'_,_ _3_)","(_'_f_r_e_q_3_'_,_ _4_)","(_'_f_r_e_q_3_'_,_ _5_)","(_'_f_r_e_q_3_'_,_ _6_)","(_'_f_r_e_q_3_'_,_ _7_)","(_'_f_r_e_q_3_'_,_ _8_)","(_'_i_n_t_e_r_v_a_l_'_,_ _'_'_)","(_'_m_a_x_'_,_ _1_)","(_'_m_a_x_'_,_ _2_)","(_'_m_a_x_'_,_ _3_)","(_'_m_a_x_'_,_ _4_)","(_'_m_a_x_'_,_ _5_)","(_'_m_a_x_'_,_ _6_)","(_'_m_a_x_'_,_ _7_)","(_'_m_a_x_'_,_ _8_)","(_'_m_i_n_'_,_ _1_)","(_'_m_i_n_'_,_ _2_)","(_'_m_i_n_'_,_ _3_)","(_'_m_i_n_'_,_ _4_)","(_'_m_i_n_'_,_ _5_)","(_'_m_i_n_'_,_ _6_)","(_'_m_i_n_'_,_ _7_)","(_'_m_i_n_'_,_ _8_)","(_'_r_m_s_'_,_ _1_)","(_'_r_m_s_'_,_ _2_)","(_'_r_m_s_'_,_ _3_)","(_'_r_m_s_'_,_ _4_)","(_'_r_m_s_'_,_ _5_)","(_'_r_m_s_'_,_ _6_)","(_'_r_m_s_'_,_ _7_)","(_'_r_m_s_'_,_ _8_)","(_'_s_u_b_j_e_c_t___i_d_'_,_ _'_'_)"
0,1.0,-0.01,-0.01,0.04,0.00,0.01,0.00,-0.01,0.00,0.00,-0.01,-0.03,0.00,0.01,0.02,0.00,0.01,0.01,0.00,0.04,-0.01,-0.01,0.01,0.01,0.01,0.0,-0.00003,-0.00007,-0.00007,-0.00005,-0.00004,-0.00003,-0.00003,-0.00003,-0.00003,-0.00007,-0.00007,-0.00005,-0.00004,-0.00003,-0.00003,-0.00003,0.000015,0.000025,0.000031,0.000019,0.000015,0.000013,0.000014,0.000014,1.0
1,1.0,0.00,0.01,0.00,0.02,0.00,0.00,0.00,0.00,0.02,0.00,0.03,0.02,0.00,0.00,0.00,0.00,0.01,0.03,0.02,0.01,-0.01,0.00,0.00,0.00,1.0,-0.00004,-0.00006,-0.00008,-0.00007,-0.00004,-0.00004,-0.00003,-0.00004,-0.00004,-0.00006,-0.00008,-0.00007,-0.00004,-0.00004,-0.00003,-0.00004,0.000016,0.000023,0.000024,0.000023,0.000017,0.000014,0.000013,0.000015,1.0
2,1.0,0.00,-0.01,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.01,-0.02,0.02,0.00,-0.01,0.00,0.00,0.02,-0.01,-0.01,0.00,0.00,0.00,0.00,0.01,2.0,-0.00004,-0.00007,-0.00008,-0.00005,-0.00003,-0.00004,-0.00003,-0.00004,-0.00004,-0.00007,-0.00008,-0.00005,-0.00003,-0.00004,-0.00003,-0.00004,0.000014,0.000024,0.000029,0.000019,0.000015,0.000015,0.000014,0.000014,1.0
3,1.0,-0.01,-0.02,0.01,-0.01,0.00,0.00,0.00,0.00,0.00,0.02,0.02,0.02,-0.01,0.00,0.01,0.00,0.00,0.01,0.02,0.01,0.01,0.00,0.01,0.01,19.0,-0.00004,-0.00008,-0.00009,-0.00006,-0.00004,-0.00006,-0.00003,-0.00003,-0.00004,-0.00008,-0.00009,-0.00006,-0.00004,-0.00006,-0.00003,-0.00003,0.000017,0.000031,0.000042,0.000022,0.000015,0.000020,0.000015,0.000014,1.0
4,1.0,-0.01,0.02,0.03,0.01,0.00,-0.01,0.01,-0.01,0.01,0.00,0.03,0.02,0.01,0.00,0.01,0.01,0.00,0.03,-0.01,0.01,0.02,0.01,0.01,0.00,20.0,-0.00003,-0.00010,-0.00009,-0.00007,-0.00004,-0.00004,-0.00004,-0.00005,-0.00003,-0.00010,-0.00009,-0.00007,-0.00004,-0.00004,-0.00004,-0.00005,0.000015,0.000032,0.000052,0.000023,0.000014,0.000015,0.000016,0.000017,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,6.0,-0.05,0.04,0.01,0.04,0.02,0.09,0.10,0.33,0.27,0.04,0.03,0.01,0.31,0.15,0.16,0.10,0.10,0.02,0.01,0.00,0.08,0.00,-0.07,0.13,44.0,-0.00032,-0.00017,-0.00009,-0.00009,-0.00030,-0.00022,-0.00032,-0.00032,-0.00032,-0.00017,-0.00009,-0.00009,-0.00030,-0.00022,-0.00032,-0.00032,0.000116,0.000071,0.000037,0.000041,0.000129,0.000096,0.000118,0.000117,36.0
2475,6.0,0.03,0.02,0.03,0.02,0.01,0.08,0.14,-0.05,0.04,0.03,0.06,0.00,-0.02,0.11,0.15,0.03,0.05,0.29,0.04,0.05,0.02,0.05,0.05,0.04,45.0,-0.00035,-0.00014,-0.00006,-0.00008,-0.00018,-0.00015,-0.00018,-0.00033,-0.00035,-0.00014,-0.00006,-0.00008,-0.00018,-0.00015,-0.00018,-0.00033,0.000068,0.000038,0.000027,0.000033,0.000101,0.000074,0.000066,0.000070,36.0
2476,6.0,-0.01,0.19,0.04,0.02,0.23,0.04,-0.02,0.01,0.21,0.10,0.10,0.00,0.19,0.01,-0.01,0.03,0.10,0.01,0.09,0.11,0.00,0.03,0.00,0.02,57.0,-0.00024,-0.00021,-0.00012,-0.00020,-0.00035,-0.00054,-0.00014,-0.00019,-0.00024,-0.00021,-0.00012,-0.00020,-0.00035,-0.00054,-0.00014,-0.00019,0.000066,0.000074,0.000037,0.000081,0.000169,0.000141,0.000054,0.000059,36.0
2477,6.0,0.01,0.01,0.01,0.03,0.09,0.01,0.03,0.07,-0.01,0.01,0.03,0.04,0.07,0.12,0.08,0.14,0.01,-0.01,-0.01,0.01,0.13,0.09,0.06,0.02,58.0,-0.00016,-0.00007,-0.00006,-0.00011,-0.00027,-0.00027,-0.00021,-0.00030,-0.00016,-0.00007,-0.00006,-0.00011,-0.00027,-0.00027,-0.00021,-0.00030,0.000047,0.000029,0.000026,0.000050,0.000116,0.000161,0.000082,0.000093,36.0
2478,6.0,0.02,0.01,-0.01,-0.01,0.25,0.17,0.02,0.07,-0.01,0.00,0.00,0.04,0.09,-0.05,0.00,0.10,0.03,0.03,0.01,0.04,0.09,-0.01,0.07,0.05,59.0,-0.00042,-0.00008,-0.00006,-0.00014,-0.00028,-0.00055,-0.00023,-0.00031,-0.00042,-0.00008,-0.00006,-0.00014,-0.00028,-0.00055,-0.00023,-0.00031,0.000116,0.000027,0.000028,0.000042,0.000161,0.000161,0.000085,0.000086,36.0

In [ ]:
final_catch22.columns = ['class','freq1_1','freq1_2','freq1_3','freq1_4','freq1_5','freq1_6','freq1_7','freq1_8',
                         'freq2_1','freq2_2','freq2_3','freq2_4','freq2_5','freq2_6','freq2_7','freq2_8',
                         'freq3_1','freq3_2','freq3_3','freq3_4','freq3_5','freq3_6','freq3_7','freq3_8','interval',
                         'max_1','max_2','max_3','max_4','max_5','max_6','max_7','max_8',
                         'min_1','min_2','min_3','min_4','min_5','min_6','min_7','min_8',
                         'rms_1','rms_2','rms_3','rms_4','rms_5','rms_6','rms_7','rms_8','subject_id']
print(final_catch22.head())

   class  freq1_1  freq1_2  freq1_3  freq1_4  freq1_5  freq1_6  freq1_7  \
0    1.0    -0.01    -0.01     0.04     0.00     0.01     0.00    -0.01
1    1.0     0.00     0.01     0.00     0.02     0.00     0.00     0.00
2    1.0     0.00    -0.01     0.00     0.01     0.00     0.01     0.00
3    1.0    -0.01    -0.02     0.01    -0.01     0.00     0.00     0.00
4    1.0    -0.01     0.02     0.03     0.01     0.00    -0.01     0.01

   freq1_8  freq2_1  freq2_2  freq2_3  freq2_4  freq2_5  freq2_6  freq2_7  \
0     0.00     0.00    -0.01    -0.03     0.00     0.01     0.02     0.00
1     0.00     0.02     0.00     0.03     0.02     0.00     0.00     0.00
2     0.00     0.00     0.01    -0.02     0.02     0.00    -0.01     0.00
3     0.00     0.00     0.02     0.02     0.02    -0.01     0.00     0.01
4    -0.01     0.01     0.00     0.03     0.02     0.01     0.00     0.01

   freq2_8  freq3_1  freq3_2  freq3_3  freq3_4  freq3_5  freq3_6  freq3_7  \
0     0.01     0.01     0.00     0.04    -0.01    -0.01     0.01     0.01
1     0.00     0.01     0.03     0.02     0.01    -0.01     0.00     0.00
2     0.00     0.02    -0.01    -0.01     0.00     0.00     0.00     0.00
3     0.00     0.00     0.01     0.02     0.01     0.01     0.00     0.01
4     0.01     0.00     0.03    -0.01     0.01     0.02     0.01     0.01

   freq3_8  interval    max_1    max_2    max_3    max_4    max_5    max_6  \
0     0.01       0.0 -0.00003 -0.00007 -0.00007 -0.00005 -0.00004 -0.00003
1     0.00       1.0 -0.00004 -0.00006 -0.00008 -0.00007 -0.00004 -0.00004
2     0.01       2.0 -0.00004 -0.00007 -0.00008 -0.00005 -0.00003 -0.00004
3     0.01      19.0 -0.00004 -0.00008 -0.00009 -0.00006 -0.00004 -0.00006
4     0.00      20.0 -0.00003 -0.00010 -0.00009 -0.00007 -0.00004 -0.00004

     max_7    max_8    min_1    min_2    min_3    min_4    min_5    min_6  \
0 -0.00003 -0.00003 -0.00003 -0.00007 -0.00007 -0.00005 -0.00004 -0.00003
1 -0.00003 -0.00004 -0.00004 -0.00006 -0.00008 -0.00007 -0.00004 -0.00004
2 -0.00003 -0.00004 -0.00004 -0.00007 -0.00008 -0.00005 -0.00003 -0.00004
3 -0.00003 -0.00003 -0.00004 -0.00008 -0.00009 -0.00006 -0.00004 -0.00006
4 -0.00004 -0.00005 -0.00003 -0.00010 -0.00009 -0.00007 -0.00004 -0.00004

     min_7    min_8     rms_1     rms_2     rms_3     rms_4     rms_5  \
0 -0.00003 -0.00003  0.000015  0.000025  0.000031  0.000019  0.000015
1 -0.00003 -0.00004  0.000016  0.000023  0.000024  0.000023  0.000017
2 -0.00003 -0.00004  0.000014  0.000024  0.000029  0.000019  0.000015
3 -0.00003 -0.00003  0.000017  0.000031  0.000042  0.000022  0.000015
4 -0.00004 -0.00005  0.000015  0.000032  0.000052  0.000023  0.000014

      rms_6     rms_7     rms_8  subject_id
0  0.000013  0.000014  0.000014         1.0
1  0.000014  0.000013  0.000015         1.0
2  0.000015  0.000014  0.000014         1.0
3  0.000020  0.000015  0.000014         1.0
4  0.000015  0.000016  0.000017         1.0

In [ ]:
final_catch22.tail(5)

,class,freq1_1,freq1_2,freq1_3,freq1_4,freq1_5,freq1_6,freq1_7,freq1_8,freq2_1,freq2_2,freq2_3,freq2_4,freq2_5,freq2_6,freq2_7,freq2_8,freq3_1,freq3_2,freq3_3,freq3_4,freq3_5,freq3_6,freq3_7,freq3_8,interval,max_1,max_2,max_3,max_4,max_5,max_6,max_7,max_8,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,rms_1,rms_2,rms_3,rms_4,rms_5,rms_6,rms_7,rms_8,subject_id
2474,6.0,-0.05,0.04,0.01,0.04,0.02,0.09,0.10,0.33,0.27,0.04,0.03,0.01,0.31,0.15,0.16,0.10,0.10,0.02,0.01,0.00,0.08,0.00,-0.07,0.13,44.0,-0.00032,-0.00017,-0.00009,-0.00009,-0.00030,-0.00022,-0.00032,-0.00032,-0.00032,-0.00017,-0.00009,-0.00009,-0.00030,-0.00022,-0.00032,-0.00032,0.000116,0.000071,0.000037,0.000041,0.000129,0.000096,0.000118,0.000117,36.0
2475,6.0,0.03,0.02,0.03,0.02,0.01,0.08,0.14,-0.05,0.04,0.03,0.06,0.00,-0.02,0.11,0.15,0.03,0.05,0.29,0.04,0.05,0.02,0.05,0.05,0.04,45.0,-0.00035,-0.00014,-0.00006,-0.00008,-0.00018,-0.00015,-0.00018,-0.00033,-0.00035,-0.00014,-0.00006,-0.00008,-0.00018,-0.00015,-0.00018,-0.00033,0.000068,0.000038,0.000027,0.000033,0.000101,0.000074,0.000066,0.000070,36.0
2476,6.0,-0.01,0.19,0.04,0.02,0.23,0.04,-0.02,0.01,0.21,0.10,0.10,0.00,0.19,0.01,-0.01,0.03,0.10,0.01,0.09,0.11,0.00,0.03,0.00,0.02,57.0,-0.00024,-0.00021,-0.00012,-0.00020,-0.00035,-0.00054,-0.00014,-0.00019,-0.00024,-0.00021,-0.00012,-0.00020,-0.00035,-0.00054,-0.00014,-0.00019,0.000066,0.000074,0.000037,0.000081,0.000169,0.000141,0.000054,0.000059,36.0
2477,6.0,0.01,0.01,0.01,0.03,0.09,0.01,0.03,0.07,-0.01,0.01,0.03,0.04,0.07,0.12,0.08,0.14,0.01,-0.01,-0.01,0.01,0.13,0.09,0.06,0.02,58.0,-0.00016,-0.00007,-0.00006,-0.00011,-0.00027,-0.00027,-0.00021,-0.00030,-0.00016,-0.00007,-0.00006,-0.00011,-0.00027,-0.00027,-0.00021,-0.00030,0.000047,0.000029,0.000026,0.000050,0.000116,0.000161,0.000082,0.000093,36.0
2478,6.0,0.02,0.01,-0.01,-0.01,0.25,0.17,0.02,0.07,-0.01,0.00,0.00,0.04,0.09,-0.05,0.00,0.10,0.03,0.03,0.01,0.04,0.09,-0.01,0.07,0.05,59.0,-0.00042,-0.00008,-0.00006,-0.00014,-0.00028,-0.00055,-0.00023,-0.00031,-0.00042,-0.00008,-0.00006,-0.00014,-0.00028,-0.00055,-0.00023,-0.00031,0.000116,0.000027,0.000028,0.000042,0.000161,0.000161,0.000085,0.000086,36.0

In [ ]:
final_catch22.shape

(2479, 51)

In [ ]:
## Training SVM Classifier
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
estimators=[]
accuracy=[]
f1_macro=[]
svc=SVC(C=100,kernel='poly',gamma=0.01,decision_function_shape='ovo')
features=final_catch22.drop(columns=["subject_id","class","interval"])
labels=final_catch22["class"]
##Training and testing set splitting
X_train, X_test,y_train,y_test= train_test_split(features,labels,test_size=0.30, random_state=1, shuffle=False)
## Data normalization
mean = X_train.mean(axis=0)
std = X_train.std(axis=0)
X_train -= mean
X_train /= std
X_test -= mean
X_test /= std
svc.fit(X_train,y_train)
y_test_pred=svc.predict(X_test)
y=f1_score(y_test,y_test_pred,average='macro') 
x=confusion_matrix(y_test,y_test_pred)
a=accuracy_score(y_test,y_test_pred)
print("F1 Score: ", y)
print("Confusion Matrix: \n")
print(x)
print("Accuracy: ", a)
#estimators.append(print_estimator_name(svc))
f1_macro.append(y)
accuracy.append(a)
plt.show()

F1 Score:  0.05128205128205129
Confusion Matrix:

[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  5  46  60 159  60   0]
 [ 93  63 193  65   0   0]]
Accuracy:  0.08064516129032258